package org.yashgamerx.notepad.view;

import javafx.beans.binding.Bindings;
import javafx.beans.property.BooleanProperty;
import javafx.beans.property.ObjectProperty;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Label;
import javafx.scene.control.Tab;
import javafx.scene.control.TextArea;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import lombok.Getter;
import lombok.extern.java.Log;
import org.yashgamerx.notepad.view.find.FindBarView;
import org.yashgamerx.notepad.viewmodel.NotepadTabViewModel;
import org.yashgamerx.notepad.viewmodel.NotepadViewModel;

import java.io.IOException;

/**
 * The visual component for a single notepad tab.
 *
 * <p>SRP: this class is solely responsible for rendering a tab and binding
 * JavaFX properties to the {@link NotepadTabViewModel}. No business logic
 * or state lives here.</p>
 *
 * <h3>Changes from original</h3>
 * <ul>
 *   <li>Exposes {@link #getFindBar()} so {@link NotepadView} can wire the
 *       find shortcut without reaching inside this class's internals.</li>
 *   <li>Holds a typed reference to {@link NotepadTabViewModel} via
 *       {@code @Getter} — no more unsafe {@code getUserData()} cast.</li>
 * </ul>
 */
@Log
@Getter
public class NotepadTabView extends Tab {

    // FXML fields
    @FXML private Tab      tab;
    @FXML private VBox     contentRoot;
    @FXML private TextArea textArea;
    @FXML private Label    numberOfLines;
    @FXML private Label    characters;
    @FXML private Label    zoomPercentage;

    // Child view — built programmatically (no FXML needed for a simple toolbar)
    private final FindBarView findBar = new FindBarView();

    // ViewModel — accessible via getViewModel() generated by @Getter
    private NotepadTabViewModel viewModel;

    public NotepadTabView() {
        loadFXML();
    }

    private void loadFXML() {
        var loader = new FXMLLoader(
                getClass().getResource("/org/yashgamerx/notepad/view/notepad-tab-template.fxml")
        );
        loader.setRoot(this);
        loader.setController(this);
        try {
            loader.load();
        } catch (IOException e) {
            log.severe("Failed to load notepad-tab-template.fxml: " + e.getMessage());
        }
    }

    @FXML
    private void initialize() {
        // Insert the find bar between the TextArea and the status HBox.
        // contentRoot is the VBox declared in the FXML.
        contentRoot.getChildren().add(1, findBar);
    }

    /**
     * Binds this view to the provided ViewModel and shared properties.
     *
     * @param viewModel       the tab-specific ViewModel
     * @param wordWrapProperty shared word-wrap toggle from the main ViewModel
     * @param fontProperty    shared font property from the main ViewModel
     */
    public void bind(
            NotepadTabViewModel viewModel,
            BooleanProperty wordWrapProperty,
            ObjectProperty<Font> fontProperty
    ) {
        this.viewModel = viewModel;

        textArea.textProperty().bindBidirectional(viewModel.contentProperty());
        textArea.wrapTextProperty().bind(wordWrapProperty);
        textArea.fontProperty().bind(fontProperty);

        tab.textProperty().bind(viewModel.displayTitleBinding());
        numberOfLines.textProperty().bind(viewModel.lineCountBinding());
        characters.textProperty().bind(viewModel.characterCountBinding());

        var percentBinding = Bindings.createDoubleBinding(
                () -> (fontProperty.get().getSize() / NotepadViewModel.DEFAULT_FONT_SIZE) * 100.0,
                fontProperty
        );
        zoomPercentage.textProperty().bind(percentBinding.asString("%.0f%%"));

        // Wire the find bar to this tab's ViewModel and TextArea
        findBar.bind(viewModel.getFindViewModel(), textArea);
    }

    /**
     * Releases all JavaFX binding references.
     * Must be called when the tab is removed to avoid memory leaks.
     */
    public void unbind() {
        if (viewModel == null) return;

        textArea.textProperty().unbindBidirectional(viewModel.contentProperty());
        textArea.wrapTextProperty().unbind();
        textArea.fontProperty().unbind();
        tab.textProperty().unbind();
        numberOfLines.textProperty().unbind();
        characters.textProperty().unbind();
        zoomPercentage.textProperty().unbind();
    }
}
