package org.yashgamerx.notepad.view;

import javafx.beans.binding.Bindings;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.BooleanProperty;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Label;
import javafx.scene.control.Tab;
import javafx.scene.control.TextArea;
import javafx.scene.text.Font;
import lombok.Getter;
import lombok.extern.java.Log;
import org.yashgamerx.notepad.viewmodel.NotepadTabViewModel;
import org.yashgamerx.notepad.viewmodel.NotepadViewModel;

import java.io.IOException;

/**
 * The visual component for a single notepad tab.
 *
 * <h3>Changes from the original</h3>
 * <ul>
 *   <li>{@code BASE_FONT_SIZE} is sourced from {@link NotepadViewModel#DEFAULT_FONT_SIZE}
 *       instead of a locally duplicated constant.</li>
 *   <li>Holds a reference to the bound {@link NotepadTabViewModel} so that
 *       {@link NotepadView} can retrieve it via a typed accessor instead of
 *       the unsafe {@code (NotepadTabViewModel) tab.getUserData()} cast.</li>
 * </ul>
 */
@Log
@Getter
public class NotepadTabView extends Tab {

    // FXML Elements
    @FXML
    private Tab tab;
    @FXML
    private TextArea textArea;
    @FXML
    private Label numberOfLines;
    @FXML
    private Label characters;
    @FXML
    private Label zoomPercentage;

    // ViewModel — accessible via getViewModel() generated by @Getter
    private NotepadTabViewModel viewModel;

    public NotepadTabView() {
        loadFXML();
    }

    private void loadFXML() {
        var loader = new FXMLLoader(
                getClass().getResource("/org/yashgamerx/notepad/view/notepad-tab-template.fxml")
        );
        loader.setRoot(this);
        loader.setController(this);

        try {
            loader.load();
        } catch (IOException e) {
            log.severe("Failed to load notepad-tab-template.fxml");
        }
    }

    /**
     * Binds this view to the provided ViewModel and shared properties.
     *
     * @param viewModel      the tab-specific ViewModel
     * @param wordWrapProperty shared word-wrap toggle from the main ViewModel
     * @param fontProperty   shared font property from the main ViewModel
     */
    public void bind(
            NotepadTabViewModel viewModel,
            BooleanProperty wordWrapProperty,
            ObjectProperty<Font> fontProperty
    ) {
        this.viewModel = viewModel;

        textArea.textProperty().bindBidirectional(viewModel.contentProperty());
        textArea.wrapTextProperty().bind(wordWrapProperty);
        textArea.fontProperty().bind(fontProperty);

        tab.textProperty().bind(viewModel.displayTitleBinding());
        numberOfLines.textProperty().bind(viewModel.lineCountBinding());
        characters.textProperty().bind(viewModel.characterCountBinding());

        // Use the canonical default from NotepadViewModel — single source of truth.
        var percentBinding = Bindings.createDoubleBinding(
                () -> (fontProperty.get().getSize() / NotepadViewModel.DEFAULT_FONT_SIZE) * 100.0,
                fontProperty
        );
        zoomPercentage.textProperty().bind(percentBinding.asString("%.0f%%"));
    }

    /**
     * Cleans up all bindings when this tab is removed.
     */
    public void unbind() {
        if (viewModel == null) return;

        textArea.textProperty().unbindBidirectional(viewModel.contentProperty());
        textArea.wrapTextProperty().unbind();
        textArea.fontProperty().unbind();
        tab.textProperty().unbind();
        numberOfLines.textProperty().unbind();
        characters.textProperty().unbind();
        zoomPercentage.textProperty().unbind();
    }
}
